services:
  - type: web
    name: rumor-cms
    rootDir: cms
    env: node
    plan: starter
    buildCommand: yarn install && yarn install-plugins && yarn build
    startCommand: yarn start
    healthCheckPath: /_health
    region: frankfurt
    branch: main
    repo: https://github.com/playfield-art/rumor.git
    autoDeploy: false
    envVars:
      - key: NODE_VERSION
        value: ~16.13.0
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        fromDatabase:
          name: rumor-cms
          property: connectionString
      - key: JWT_SECRET
        generateValue: true
      - key: ADMIN_JWT_SECRET
        generateValue: true
      - key: APP_KEYS
        generateValue: true
      - key: API_TOKEN_SALT
        generateValue: true

databases:
  - name: rumor-cms
    plan: starter
    region: frankfurt
